### ISSUE TITLE
Adding maintainers or transferring to adopted-ember-addons

### ISSUE THREAD

**Issue by rwwagner90** [aomran/ember-cli-chart#114]
Hi @aomran would you be open to giving some more maintainers access to this repo and npm and/or transferring to https://github.com/adopted-ember-addons?

**Comment by aomran** [comment]
@rwwagner90 I am open to adding people as collaborators. Are you interested in doing this?

**Comment by rwwagner90** [comment]
@aomran yeah, that would be great!

**Comment by rwwagner90** [comment]
@aomran do you mind adding me? My PR has been open quite awhile, and I would like to merge it.

**Comment by rwwagner90** [comment]
I would highly recommend transferring to adopted-ember-addons, if you do not have the time to maintain this though. We would love to revitalize it!

**Comment by aomran** [comment]
@rwwagner90 I invited you as a collaborator. Sorry things have been crazy lately :(

**Comment by rwwagner90** [comment]
@aomran no worries!
