### ISSUE TITLE
Bar Charts not updating correctly on dataset change

### ISSUE THREAD

**Issue by sbatson5** [aomran/ember-cli-chart#29]
Thanks for all the work on ember-cli-chart.  I have an issue where we track interest payments over sets of years, with 2 data points:
<img width="510" alt="screen shot 2015-07-10 at 1 38 11 pm" src="https://cloud.githubusercontent.com/assets/881981/8624846/eff2ce4c-2708-11e5-8b93-9603e67a15b0.png">

However, when the loan is paid off faster than 10 years, the chart should update.  Here is the default behavior:
<img width="538" alt="screen shot 2015-07-10 at 11 44 39 am" src="https://cloud.githubusercontent.com/assets/881981/8624853/ffae12c4-2708-11e5-8033-25bf450e4861.png">

To solve this, I edited chart-data-updater to check to see if the bars length matched our new dataset length:
 ```javascript
    if (chart.datasets.length !== datasets.length) {
      return this.set('redraw', true);
    } else if (chart.datasets[0].bars.length !== datasets[0].data.length) {
      return this.set('redraw', true);
    }
```

Is there a better way to do this?  Would it make sense to also confirm that the type is bar?

**Comment by aomra015** [comment]
@sbatson5 the `chart.datasets[0].bars` won't work if it's not a bar chart as you might have guessed. `chart.datasets[0].bars !== 'undefined'` should do the trick.

It seems we keep running into edge cases with the automatic updating. I'm hoping Chartjs version 2 will fix all of these hacks once it's stable.

**Comment by sbatson5** [comment]
what if you passed the type to chart-data-updater?
```javascript
    var redraw = ChartDataUpdater.create({
      data: data,
      chart: chart,
      type: type
    }).updateByType();
```

Then specified the type:
```javascript
    if (chart.datasets.length !== datasets.length) {
      return this.set('redraw', true);
    } else if (this.get('type') === 'Bar' && chart.datasets[0].bars.length !== datasets[0].data.length) {
      return this.set('redraw', true);
    }
```

**Comment by sbatson5** [comment]
Misunderstood your first reply.  Revised to:
```javascript
    if (chart.datasets.length !== datasets.length) {
      return this.set('redraw', true);
    } else if (typeof chart.datasets[0].bars !== 'undefined') {
      if (chart.datasets[0].bars.length !== datasets[0].data.length) {
        return this.set('redraw', true);
      }
    }
```

**Comment by sbatson5** [comment]
@aomra015 Opened a PR with the above revision and unit test.
https://github.com/aomra015/ember-cli-chart/pull/30

**Comment by sbatson5** [comment]
@aomra015 Have you had a chance to look at the PR I opened regarding updating bar charts on dataset length changes?  Let me know if it looks good or if you see any issues.

**Comment by aomra015** [comment]
I'll try to find some time this weekend to review this. Thanks !

**Comment by aomran** [comment]
merged

**Comment by sbatson5** [comment]
:+1: Thanks!
