### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by nicosandller** [aomran/ember-cli-chart#35]
Hey, 

I was looking to make it responsive, and Chartjs has some support for this option as part of the global chart configuration option. Do you think you could extend these options to this ember adaptation for chartsjs?

Alternatively can you guide me through how it could be implemented? I'd be happy to do the job and create a pull request.

thanks.

**Comment by aomran** [comment]
You can do this right now by passing an options object to the component:

```hbs
{{ember-chart type=CHARTTYPE data=CHARTDATA options=CHARTOPTIONS}}
```

You can also set it globally:

```js
Chart.defaults.global.responsive = true;
```

**Comment by nicosandller** [comment]
Thanks I didn't see that.

:)

**Comment by acerov** [comment]
Hi,

I did `Chart.defaults.global.responsive = true;`
and also tried passing options but my charts are still not responsive, I don't know where to look next.
I am using Ember 1.13.9
