### ISSUE TITLE
Pie chart updating breaks when label is set to nil

### ISSUE THREAD

**Issue by constantm** [aomran/ember-cli-chart#38]
Something minor, but when labels are set to nil (in cases where they don't actually get used), the data updating breaks. This is due to [this line here](https://github.com/aomran/ember-cli-chart/blob/master/addon/chart-data-updater.js#L58). Since labels will be set most of the time, this is a rather extreme edge case. However, I suggest an exception be raised or something if label is set to nil.

**Comment by aomran** [comment]
does https://github.com/aomran/ember-cli-chart/pull/39 address this issue?

**Comment by constantm** [comment]
Looking at the PR, it most probably fixes the issue. I'll have a look when I have a moment and report back here if it doesn't work. :)
