### ISSUE TITLE
Pie chart does not come back after reaching a sum of zero

### ISSUE THREAD

**Issue by tinaboyce** [aomran/ember-cli-chart#40]
I have a pie chart that has updated values passed into it. 

However, if update values does reach a sum of zero, the pie chart disappears, which is a ChartJS behaviour, but no amount of non-zero values can bring it back unless I refresh the page.

Note: I can get around with a hack for now, that is if sum of values is 0, put in a non-zero with color/highlight the same colour as the background-color value to preserve the pie.

**Comment by sbatson5** [comment]
I ran into a similar issue.  I wrapped my chart component in an `{{#if}}`.  I had a computed property that returned true if if the data was greater than 0.  If it was 0, the chart component would be hidden and would therefore re-render if we received new data.

But that's also kind of a hack solution.

**Comment by aomran** [comment]
Can you check if the latest version resolves this?  https://github.com/aomran/ember-cli-chart/pull/54.

**Comment by aomran** [comment]
I've verified this doesn't happen in latest version.
