### ISSUE TITLE
Chart.js v2 compatibility

### ISSUE THREAD

**Issue by Turbo87** [aomran/ember-cli-chart#49]
Are there any plans to make this addon compatible with the upcoming v2 release of Chart.js? I'm specifically looking forward to using their time-series charts.

**Comment by makepanic** [comment]
`chart.js@2.0.0` is now released https://github.com/nnnick/Chart.js/releases/tag/v2.0.0

**Comment by chvonrohr** [comment]
👍

**Comment by SeyZ** [comment]
@aomran update ? :)

**Comment by aomran** [comment]
Yes I will be updating the addon to use v2 as soon as I can. I'm really looking forward to the auto-updating charts because that'll remove some code we had to add here.

**Comment by GiovanniL19** [comment]
Needing Chartjs 2 a lot now. They have added some great features

**Comment by aomran** [comment]
https://github.com/aomran/ember-cli-chart/pull/54

**Comment by GiovanniL19** [comment]
Thank you very much for your hard work!! :D

**Comment by steveclarkin** [comment]
Just another party interested to see ember-cli-chart support ChartJS v2. How can we help? Thanks for your work on this! :)

**Comment by aomran** [comment]
note that #54 was merged so version 3 is now available on npm
