### ISSUE TITLE
Chart,  hidden or display: none and display:block 

### ISSUE THREAD

**Issue by cmonzon44** [aomran/ember-cli-chart#52]
Hi, when i need to hide my chart with the attribute hidden, and after action on a button, I show the div which contains the chart, but the chart don't appear.
the same when I insert style="display:none;" in my div and after action to change to display:block;

 why chart is not appear?
or how I do to insert the component since my action in controller when the user clicked the button?
thanks

**Comment by aomran** [comment]
@cmonzon44 can you provide more information? I'm not understanding the issue.

**Comment by OakBehringer** [comment]
I can help. 

style:
```
.hidden { display: none; }
```

In your controller:
```
showChart: false,

init() {
  this._super(...arguments);
  // show the chart after two seconds:
  Ember.run.later(() => {
    this.set('showChart', true);
  }, 2000)
},

```

in your template.hbs:
```
{{#if showChart}}
	<div style="height: 500px; width: 500px; border: 1px solid pink;">
		{{ember-chart type="Bar" data=chartData width=500 height=500}}
	</div>
{{/if}}

<div class={{if showChart "" "hidden"}}>
	<div style="height: 500px; width: 500px; border: 1px solid pink;">
		{{ember-chart type="Bar" data=chartData width=500 height=500}}
	</div>
</div>
```

The first chart shows, but the second does not. (The pink box does show up). It is not unusual to have your chart wrapped in a component that might first render the {{ember-chart ... in a div that is styled to display:none.

**Comment by aomran** [comment]
this addon is just a wrapper around the chartjs library.
