### ISSUE TITLE
Updated options attr doesn't take effect

### ISSUE THREAD

**Issue by jeremytm** [aomran/ember-cli-chart#53]
The updateChart function doesn't actually get up-to-date options via this.get('options') when the options observer fires.

This prevents turning animation on or off (for example), without removing and re-adding the entire chart addon component.

**Comment by aomran** [comment]
The next major version is being worked on here: https://github.com/aomran/ember-cli-chart/pull/54. I haven't soled this issue though -- I'm not sure if chartjs supports this option (redrawing/updating a chart with new options).

**Comment by marclundgren** [comment]
Is this still being worked on? It doesn't seem to have been fixed in the latest release.

**Comment by aomran** [comment]
Version 2.5 of Chartjs is supposed to support updating of charts from options. Keep an eye on #67

**Comment by Techn1x** [comment]
So I've updated to ember-cli-chart 3.3.0 (which should be chartjs 2.6) but it doesn't look like changing attributes in my chart options is working, am I missing something?

**Comment by aomran** [comment]
duplicates https://github.com/aomran/ember-cli-chart/issues/78
