### ISSUE TITLE
Cannot change chart color

### ISSUE THREAD

**Issue by alyakan** [aomran/ember-cli-chart#55]
Is there anyway I can change the chart's color ? It is always grey and I'm sure I'm using the correct format for data as referenced from chartjs.org

`var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "My First dataset",
            backgroundColor: "rgba(255,99,132,0.2)",
            borderColor: "rgba(255,99,132,1)",
            borderWidth: 1,
            hoverBackgroundColor: "rgba(255,99,132,0.4)",
            hoverBorderColor: "rgba(255,99,132,1)",
            data: [65, 59, 80, 81, 56, 55, 40],
        }
    ]
};`

**Comment by alyakan** [comment]
It seems that the attribute `backgroundColor: "rgba(255,99,132,0.2)"` should be changed to `fillColor: "rgba(255,99,132,0.2)"`. It is weird that the package is using different attribute names than what is found in the documentation of Chart.js and it is not concerning this attribute only but many others. I had to go throught the package files to find out which attribute is which, please look into this matter :)

**Comment by robikovacs** [comment]
@aomran, is giving that name, *fillColor*, intentional?

**Comment by aomran** [comment]
We're now on the latest version of chartjs so the documentation at chartjs.org should be correct and work here.
