### ISSUE TITLE
Doughnut, Pie and Polar Area charts do not render

### ISSUE THREAD

**Issue by alyakan** [aomran/ember-cli-chart#56]
There's no error in the console so it must be some logical error that's keeping them from rendering on the screen, or maybe they render but something is hiding them. @aomran

**Comment by aomran** [comment]
Note that the documentation on chartjs is for the latest version. This addon is still on v1 until I upgrade it.

**Comment by alyakan** [comment]
Have you got any documentation on how to set them up here asap please ? @aomran

**Comment by curtisclark** [comment]
v1 docs for ChartJS can be found here: https://github.com/chartjs/Chart.js/tree/v1.1.1/docs

I had the same problem as you, but the data structure for the pie and doughnut charts specified in those docs works. Use that doc until this plugin is updated to v2.

Curiosity urges me to ask for an ETA on the upgrade to v2 ChartJS...

**Comment by aomran** [comment]
This addon is using the latest version of chartjs so the documentation should match now.
