### ISSUE TITLE
Line chart options not working

### ISSUE THREAD

**Issue by jtsom** [aomran/ember-cli-chart#61]
Trying to use some of the options with a line chart seems to not be implemeted?

Using data such as:

```
labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "My First dataset",
            fill: false,
            lineTension: 0.1,

            data: [65, 59, 80, 81, 56, 55, 40],

        }
    ]
```

the fill and lineTension options are not being recognized. The line chart always shows filled, and with a curve.

**Comment by jtsom** [comment]
As an options.... please release the latest version, so we can use the latest Chartjs... or at least give instructions on how to use the latest...

**Comment by aomran** [comment]
I apologize for not releasing the latest version -- it's been sitting in that branch for too long. I'll try to find some time for that this week. Again I'm sorry for the delay.

**Comment by ajb223** [comment]
I am unable to set the radius: 0 in the Line chart to remove the data points from the chart. Was this issue ever resolved? I am using the latest release on ember-cli-chart on npm.

**Comment by aomran** [comment]
We're now on latest so everything should work as documented on chartjs.org
