### ISSUE TITLE
Cannot create stacked (scatter plot) chart

### ISSUE THREAD

**Issue by maxwerr** [aomran/ember-cli-chart#66]
I'm trying to reproduce the effect demonstrated in [this jsbin](https://jsbin.com/bezidevawi/edit?html,js,output), but the same options for "scale" etc are making the data not render. Not sure if the `stacked` variable is working differently than expected or if I'm missing something.

**Comment by aomran** [comment]
this is just a wrapper around the chartjs library

**Comment by maxwerr** [comment]
Ok sorry. I figured if it was possible in chartjs it would be possible using this addon, since it is just a wrapper.
