### ISSUE TITLE
Production build of ember-cli-chart

### ISSUE THREAD

**Issue by Techn1x** [aomran/ember-cli-chart#77]
Hi everyone,

Firstly, thanks for keeping this repo alive and up to date :)

I've recently updated from 3.2.0 to 3.3.0 of ember-cli-chart, and while it all worked on my local dev machine as a dev build, when I do a production build, I get this error
```
ReferenceError: Chart is not defined
    at a.didInsertElement (vendor-fc2065f….js:formatted:46192)
    at a.trigger (vendor-fc2065f….js:formatted:28417)
    at a.n [as trigger] (vendor-fc2065f….js:formatted:27745)
    at n.didCreate (vendor-fc2065f….js:formatted:18178)
    at e.commit (vendor-fc2065f….js:formatted:11801)
    at r.e.commit (vendor-fc2065f….js:formatted:11951)
    at r.commit (vendor-fc2065f….js:formatted:16914)
    at t.e._renderRoots (vendor-fc2065f….js:formatted:17779)
    at t.e._renderRootsTransaction (vendor-fc2065f….js:formatted:17793)
    at t.e._renderRoot (vendor-fc2065f….js:formatted:17754)
```

Looks like it's not including charts.js when doing a prod build? The error occurs in the didInsertElement() in the ember-chart component, the specific line is here: https://github.com/aomran/ember-cli-chart/blob/master/addon/components/ember-chart.js#L14

Or am I doing something incredibly dumb? Everything was working fine with 3.2.0...

Thanks

**Comment by Techn1x** [comment]
Tried reinstalling ember-cli-chart to no avail..
```
npm uninstall ember-cli-chart
ember install ember-cli-chart
```

**Comment by Aaronfischer** [comment]
I'm also experiencing this issue as well. "Chart is not defined" in a production/canary environment.

**Comment by escobera** [comment]
Yeah, since that change I'm no longer able to use this addon on windows and cannot deploy my app to production.

@aomran any light on this one?

**Comment by Techn1x** [comment]
I build my webapp in Cloud9, so I don't think this problem is specific to windows

**Comment by escobera** [comment]
@Techn1x I think both problems stem from the same commit. On windows it wont even start the `ember server`.

On linux it works until you try to build/deploy it .

**Comment by hhff** [comment]
Also seeing this over here!

**Comment by aomran** [comment]
a related issue in the "ember-cli" project: https://github.com/ember-cli/ember-cli/issues/7034

There's a push to move away from bower in ember-cli so this is unexpected.

**Comment by aomran** [comment]
Including assets from npm will be supported official by ember-cli someday -- something to keep an eye on: https://github.com/ember-cli/ember-cli/issues/4211

**Comment by aomran** [comment]
@Techn1x can you check if the latest version of this addon works now?

**Comment by Techn1x** [comment]
I should have a chance to try it out when I get home in a couple of hours, thanks for looking into it!

**Comment by Techn1x** [comment]
It works, both dev and production build are working fine on ember-cli-chart 3.3.1
