### ISSUE TITLE
Github Tag/Release of latest

### ISSUE THREAD

**Issue by Samsinite** [aomran/ember-cli-chart#83]
Noticed that the latest release on NPM does not have a matching tag or a release on github. Would be nice to have the releases/tags on github match npm :).

Thanks for all of the work that you have put into the library.

**Comment by aomran** [comment]
updated https://github.com/aomran/ember-cli-chart/releases

thanks for the heads up :)

**Comment by Samsinite** [comment]
No problem, thanks for addressing!
