### ISSUE TITLE
didUpdateAttrs override

### ISSUE THREAD

**Issue by Techn1x** [aomran/ember-cli-chart#85]
I've noticed that instead of using observers, the component now uses `didUpdateAttrs` which seems to work well.

Any chance we could split out the update code to a separate method? Something like..
```javascript
didUpdateAttrs() {
    this._super(...arguments);
    this.updateChart();
}

updateChart() {
    // Update logic goes here
}
```

The current (minor) issue I'm having is that when I go to implement my own update logic, I extend the ember-chart component, I override `didUpdateAttrs()` where I should then be calling `this._super(...arguments)` (good practice when overriding component lifecycle hooks) but this would first call ember-chart's `didUpdateAttrs()` which has its own update logic.

If it's split out like above, I can instead just override the `updateChart()` method

Minor issue, but what do you think? I'm happy to do a PR for it

**Comment by aomran** [comment]
@Techn1x good idea -- I would appreciate a PR.

**Comment by Techn1x** [comment]
Done - sorry about the delay
