### ISSUE TITLE
chartjs plugins

### ISSUE THREAD

**Issue by Techn1x** [aomran/ember-cli-chart#86]
Sorry about the issue spam!

I am looking to use some external plugins for chart.js (eg chartjs-plugin-annotation ), and it doesn't seem to be loading... is there something special I need to do to get chartjs plugins/addons working? Or is it more likely that I've implemented it wrong

Essentially I just did an `npm install chartjs-plugin-annotation --save-dev` and then tried to use it, but nothing appears different on my charts.

Thanks for the help

**Comment by aomran** [comment]
Are you able to get it to work with just chartjs -- i.e. just adding them in an html file to see how they work?

**Comment by Techn1x** [comment]
There's a sample here;
https://codepen.io/compwright/pen/mmQMrZ

But I'll put together a simpler example of just chartjs and, a single line, and an annotation, to make sure I'm using it correctly

**Comment by jcope2013** [comment]
are you importing the javascript file from chartjs-plugin-annotation into your ember cli build?

https://github.com/kellyselden/ember-cli-node-modules-to-vendor
https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli.html

**Comment by Techn1x** [comment]
Ah, that's probably it. Thanks! I'll let you know how I go (I probably won't have time to test this out for the next 24 hours or so unfortunately)

**Comment by Techn1x** [comment]
That's all it was. Thanks for the help everyone, that ember-cli-node-modules-to-vendor addon is super helpful..

**Comment by andreiciceu** [comment]
Hello,
@Techn1x can you help me? :d
I want to do the exact same thing, to display a horizontal line on a line-chart.
I've tried node-modules-to-vendor, but I get an error that Chart is not defined (the Chart library is not loaded until a chart is drawn, so it won't bind).

Could you share your setup/config?

Many thanks

**Comment by Techn1x** [comment]
Hey @andreiciceu things are a little different now, as long as you're on Ember 3+ all you really need to do is
1. `npm install chartjs-plugin-annotation`
2. Open your `ember-cli-build.js` file, and add this line
`app.import('node_modules/chartjs-plugin-annotation/chartjs-plugin-annotation.min.js');`

Then you can use & configure the annotations plugin as normal in your chartjs options
```
plugins: {
  annotation: {
    ...
  }
}
```

**Comment by andreiciceu** [comment]
Many thanks.
The project is still on 2.x so won't apply, but I'm looking forward to an upgrade.

**Comment by Techn1x** [comment]
Well, I said 3 but anything Ember 2.15+ should be the same.

Alternatively if you're older than 2.15 you can directly download the `chartjs-plugin-annotation.min.js` file, place it in your `vendor` folder, and then do something like this
`app.import('vendor/chartjs/chartjs-plugin-annotation.min.js');`

**Comment by andreiciceu** [comment]
I tried that, but it didn't work. The `Chart` global variable does not exist at the time of the import; it's only instantiated when a chart is rendered (in a .hbs template)

**Comment by LuisAverhoff** [comment]
For me, I have the new version of ember.js and I tried to do app.import('node_modules/chartjs-plugin-labels/build/chartjs-plugin-labels.min.js') after installing chartjs-plugin-labels and adding this piece of code

```js
plugins: {
 labels: {
    ....
  }
}
```

as part of my chart options but the plugin did not take into affect. All it did was say that it could not find the chart object after importing the plugin in the component that was using ember-cli-chart. Any ideas?
