### ISSUE TITLE
Chart.js dependency

### ISSUE THREAD

**Issue by Techn1x** [aomran/ember-cli-chart#89]
Tried updating to Chart.js 2.7.0 this morning with npm. npm told me it was using 2.7.0, and that was what appeared in my node_modules folder, 
<img width="437" alt="capture3" src="https://user-images.githubusercontent.com/1049837/30300798-0732d648-979a-11e7-8a59-3b77e00c3800.PNG">

However looking at the source file my website was using it clearly said 2.6.0 at the top no matter what I did (reinstalled npm dependencies, cleared cache, etc.)

After much head-scratching, I tracked it down to this plugin, which seems to import Chart.js 2.6.0 into its own /vendor folder when installed with `npm install ember-cli-chart`, despite the fact that package.json says `^2.6.0` which should mean it should go and get the latest 2.7.0

I'm not entirely sure what the best way is to handle dependencies (I'm not very skilled at ember addons) but the approach used here doesn't seem to be fully working with how npm handles dependencies

Perhaps there could be improvements made now that the latest ember-cli allows imports directly from the node_modules folder?

For the time being, as a workaround in my project, I've modified `index.js` in the following way
```
module.exports = {
  name: 'ember-cli-chart',
  included: function(app, parentAddon) {
    this._super.included.apply(this, arguments);
    // var target = (parentAddon || app);
    // target.import('vendor/Chart.js');
  }
};
```

And imported chart.js myself as a dependency of my main webapp by;
* adding `"chart.js": "^2.7.0"` to my `package.json`
* adding the following line to `ember-cli-build.js`
`app.import('node_modules/chart.js/dist/Chart.min.js');`

**Comment by aomran** [comment]
The latest version is now using Chartjs 2.7

**Comment by Techn1x** [comment]
Thanks! If I remove my workaround, do you think I'll run into the same problem when 2.8 comes around? Ideally I'd like to be able to choose what version of Chart.JS is used (as long as it meets the package.json requirements) without having to modify this addon...
